# Pull Request Labeler configuration
# https://github.com/actions/labeler

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*.md'
          - 'docs/**'
          - 'examples/**'

tests:
  - changed-files:
      - any-glob-to-any-file:
          - '**/*_test.go'

dependencies:
  - changed-files:
      - any-glob-to-any-file:
          - 'go.mod'
          - 'go.sum'
          - 'vendor/**'

ci:
  - changed-files:
      - any-glob-to-any-file:
          - '.github/**'
          - '.goreleaser.yml'

provider:
  - changed-files:
      - any-glob-to-any-file:
          - 'windowsad/**'
          - 'main.go'
